version: "3.9"

services:
  gst-service:
    image: omicron9009/gst-service-all-in-one
    container_name: gst-service-apikey-test
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"   # Service API
      - "8050:8050"   # DB Proxy
      - "8080:8080"   # Frontend
      - "5433:5432"   # PostgreSQL (external access)
    volumes:
      - gst-pgdata:/var/lib/postgresql
      - gst-sessions:/app/sessions
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gst_dash_test
      - GSTIN=27AABFP2335E1ZM
      - USERNAME=Pgjcoca_1
    restart: unless-stopped

volumes:
  gst-pgdata:
    driver: local
  gst-sessions:
    driver: local
